[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/live"
  to = "/client.html"
  status = 200

[[redirects]]
  from = "/gym"
  to = "/gym.html"
  status = 200
